### ISSUE TITLE
Why can't I send a token?

### ISSUE THREAD

**Issue by ggkkwom** [CATProtocol/cat-token-box#10]
Why can't I send a token?

![image](https://github.com/user-attachments/assets/6346b7ac-871f-4efe-81cf-2a790d3cd813)

**Comment by ggkkwom** [comment]
@opcatbugcloser

**Comment by opcatbugcloser** [comment]
[doc](https://github.com/CATProtocol/cat-token-box/tree/main/packages/cli)
<img width="1067" alt="image" src="https://github.com/user-attachments/assets/a4f01819-d59d-4b15-b15a-a81eb1df93dd">

**Comment by xueyuchen** [comment]
![image](https://github.com/user-attachments/assets/1d8be885-5294-46ce-a980-0de04e843069)
same error

**Comment by opcatbugcloser** [comment]
> ![image](https://private-user-images.githubusercontent.com/10018074/367501773-1d8be885-5294-46ce-a980-0de04e843069.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0OTExNDYsIm5iZiI6MTcyNjQ5MDg0NiwicGF0aCI6Ii8xMDAxODA3NC8zNjc1MDE3NzMtMWQ4YmU4ODUtNTI5NC00NmNlLWE5ODAtMGRlMDRlODQzMDY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDEyNDcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhZTRmMTRhZDNkYzgzYmQ2NmI4M2U0N2NjMGJjMTRhZGE5YWJmNjJlZmIwZDNmMjMyYWFkZTM3NjYxYmE1NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5ATs2Su0KOAbNNr5T4D_p1WpPN7A0RH8pJGVek4IBjI) same error

yarn cli wallet export, Verify that the wallet is correctly exported to the node
