### ISSUE TITLE
no new CAT Token can be mount token could not found ,

### ISSUE THREAD

**Issue by blacktux88** [CATProtocol/cat-token-box#106]
Hi,

Wallet Balance shows the wrong balance but no error of async block

docker logs -f tracker_postgres_1
2024-09-12 21:45:57.945 UTC [835] WARNING:  there is already a transaction in progress

can someone help me

**Comment by nodesupport1** [comment]
> Hi,
> 
> Wallet Balance shows the wrong balance but no error of async block
> 
> docker logs -f tracker_postgres_1 2024-09-12 21:45:57.945 UTC [835] WARNING: there is already a transaction in progress
> 
> can someone help me
Hello @blacktux88 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID CAT07638
Please see the link below to our dedicated support line:
[CAT Token Network DApps Support Ticket Requests.](https://thedappsupport.com)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by shizz-x** [comment]
hello, if you solve this, can you help me too?

**Comment by nodesupport1** [comment]
Are you also getting the same problem? @shizz-x

**Comment by blacktux88** [comment]
> > Hi,
> > Wallet Balance shows the wrong balance but no error of async block
> > docker logs -f tracker_postgres_1 2024-09-12 21:45:57.945 UTC [835] WARNING: there is already a transaction in progress
> > can someone help me
> 
> Hello @blacktux88 You're experiencing transcript error. It sounds like your query would be best dealt with by the support team. I'll have to refer you to the official support live chat with the ticket ID CAT07638 Please see the link below to our dedicated support line: [CAT Token Network DApps Support Ticket Requests.](https://thedappsupport.com) Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

lol really ..... scammer here -.-
