### ISSUE TITLE
节点数据不同步

### ISSUE THREAD

**Issue by lly835** [CATProtocol/cat-token-box#107]
[Nest] 29  - 09/19/2024, 5:14:06 PM     LOG [RoutesResolver] HealthCheckController {/api}: +19ms
[Nest] 29  - 09/19/2024, 5:14:06 PM     LOG [RouterExplorer] Mapped {/api, GET} route +3ms
[Nest] 29  - 09/19/2024, 5:14:06 PM     LOG [RoutesResolver] TokenController {/api/tokens}: +0ms
[Nest] 29  - 09/19/2024, 5:14:06 PM     LOG [RouterExplorer] Mapped {/api/tokens/:tokenIdOrTokenAddr, GET} route +0ms
[Nest] 29  - 09/19/2024, 5:14:06 PM     LOG [RouterExplorer] Mapped {/api/tokens/:tokenIdOrTokenAddr/addresses/:ownerAddr/utxos, GET} route +1ms
[Nest] 29  - 09/19/2024, 5:14:06 PM     LOG [RouterExplorer] Mapped {/api/tokens/:tokenIdOrTokenAddr/addresses/:ownerAddr/balance, GET} route +0ms
[Nest] 29  - 09/19/2024, 5:14:06 PM     LOG [RouterExplorer] Mapped {/api/tokens/:tokenIdOrTokenAddr/addresses/:ownerAddr/history, GET} route +1ms
[Nest] 29  - 09/19/2024, 5:14:06 PM     LOG [RoutesResolver] MinterController {/api/minters}: +0ms
[Nest] 29  - 09/19/2024, 5:14:06 PM     LOG [RouterExplorer] Mapped {/api/minters/:tokenIdOrTokenAddr/utxos, GET} route +0ms
[Nest] 29  - 09/19/2024, 5:14:06 PM     LOG [RouterExplorer] Mapped {/api/minters/:tokenIdOrTokenAddr/utxoCount, GET} route +1ms
[Nest] 29  - 09/19/2024, 5:14:06 PM     LOG [RoutesResolver] AddressController {/api/addresses}: +0ms
[Nest] 29  - 09/19/2024, 5:14:06 PM     LOG [RouterExplorer] Mapped {/api/addresses/:ownerAddr/balances, GET} route +0ms
[Nest] 29  - 09/19/2024, 5:14:06 PM     LOG [BlockService] daemon process blocks initialized
[Nest] 29  - 09/19/2024, 5:14:06 PM     LOG [NestApplication] Nest application successfully started +2ms
Application is running on: http://[::1]:3000

不同步，会是什么原因，没报错

**Comment by ShiSheng** [comment]
same question ,mark..

**Comment by opcatdev** [comment]
checkout the latest code
