### ISSUE TITLE
relation "block" does not exist

### ISSUE THREAD

**Issue by 0xb7ee** [CATProtocol/cat-token-box#109]
![image](https://github.com/user-attachments/assets/3c11fb1a-2e65-4568-8868-8ff3ff30bd97)
fetch all balance failed!
relation "block" does not exist
No tokens found!
fetch tracker status failed
relation "block" does not exist
Get Balance failed!
tracker status is abnormal
when I run yarn cli wallet balances I get this error what's wrong with it

**Comment by opcatdev** [comment]
https://github.com/CATProtocol/cat-token-box/issues/134#issuecomment-2377677363
