### ISSUE TITLE
fetch minters failed

### ISSUE THREAD

**Issue by dino-ma** [CATProtocol/cat-token-box#118]
<img width="697" alt="image" src="https://github.com/user-attachments/assets/8ed64815-6a87-4831-8c98-b98e663348af">
<img width="1346" alt="image" src="https://github.com/user-attachments/assets/ad5f501a-95a7-4480-a187-7a08274a9a9b">

how to solve the problem？

**Comment by groomiee** [comment]
same issue

**Comment by catchstar** [comment]
same

**Comment by bmwyzb1** [comment]
same

**Comment by justswash** [comment]
This is relelated to tokens deployed on V2. If you have this issue then your node is still running V1.
Go inside your cat-token-box folder and pull the latest changes (git pull)
Then build the project again (yarn install && yarn build)

The issue will be fixed

**Comment by pirateOfGit** [comment]
> This is relelated to tokens deployed on V2. If you have this issue then your node is still running V1. Go inside your cat-token-box folder and pull the latest changes (git pull) Then build the project again (yarn install && yarn build)
> 
> The issue will be fixed

This works

**Comment by blacktux88** [comment]
thanks now it seems to go a step  ahead 

$ node dist/main mint -i c468e99ac3b533e503eac5ccf4f0e3362772f80cead8b7f71d802305d02f73d0_0 10

now it tells me that token limit is exceeds but there are 30% less
The number of minted tokens exceeds the limit!

**Comment by pirateOfGit** [comment]
That is because the limit per mint is 3. You have input 10

**Comment by justswash** [comment]
> thanks now it seems to go a step ahead
> 
> $ node dist/main mint -i c468e99ac3b533e503eac5ccf4f0e3362772f80cead8b7f71d802305d02f73d0_0 10
> 
> now it tells me that token limit is exceeds but there are 30% less The number of minted tokens exceeds the limit!

Dont enter the limit and it will auto mint at the limit.

**Comment by blacktux88** [comment]
> That is because the limit per mint is 3. You have input 10

ahh i thought this is the repeat count , is there an mint repeat option ?

**Comment by justswash** [comment]
> > That is because the limit per mint is 3. You have input 10
> 
> ahh i thought this is the repeat count , is there an mint repeat option ?

No theres no option for repeat mint. Youll have to write a script to mint in a loop
