### ISSUE TITLE
每一笔交易都会进行拆分，相当于 cat20mint一次  拿了两次手续费 这个可以优化吗？

### ISSUE THREAD

**Issue by yutou123** [CATProtocol/cat-token-box#119]
每一笔交易都会进行拆分，相当于 cat20 拿了两次手续费 这个可以优化吗？

<img width="517" alt="image" src="https://github.com/user-attachments/assets/822cd2a8-88d8-4e0c-b23d-df0dedb5558c">

**Comment by shizz-x** [comment]
https://github.com/CATProtocol/cat-token-box/issues/110

**Comment by yutou123** [comment]
> #110

no, I split the UTXO of fb/1fb into 100 parts, each with 0.01fb. Then, when I run the mint program, it prompts for merging. However, my wallet balance is sufficient.

我对fb 1fb 进行了utxo拆分100分 每份 0.01fb，然后 运行mint程序 它就提示进行合并。但是我的钱包余额是足够的
