### ISSUE TITLE
"No tokens found!" and "rpc_create_watchonly_wallet failed! Unauthorized"

### ISSUE THREAD

**Issue by MarkSSH** [CATProtocol/cat-token-box#12]
您好！
1、我在执行“yarn cli wallet create”的时候生成了助记词，但是报错如下内容：
rpc_create_watchonly_wallet failed!
Unauthorized

2、后台查看同步日志时候发现如下报错是否会影响同步：
ThreadRPCServer incorrect password attempt from IP:Port

3、我可以获得address，但是无法获得balances，提示我“No tokens found!”

4、同步完成该如何查看？

**Comment by opcatbugcloser** [comment]
View the docker compose log

**Comment by MarkSSH** [comment]
> View the docker compose log

我执行了docker logs -f tracker结果如下：
![image](https://github.com/user-attachments/assets/f23074b8-3784-4feb-a4f0-e3c96ef8126e)

我执行了docker compose logs结果如下：
![image](https://github.com/user-attachments/assets/8be3e835-9a39-4519-b0d3-1d98257c2a13)

**Comment by MarkSSH** [comment]
我看了一下文档说查看是否同步完成可以通过访问http://127.0.0.1:3000/api查看，我执行了“curl http://127.0.0.1:3000/api”，返回结果如下：
{"code":0,"msg":"OK","data":{"trackerBlockHeight":null,"nodeBlockHeight":null,"latestBlockHeight":null}}

**Comment by opcatbugcloser** [comment]
Tracker rpc config error

**Comment by MarkSSH** [comment]
> Tracker rpc config error

我该如何修改配置呢？我只修改了用户名和密码，一个是在.env文件中，一个是在config.json文件中

**Comment by astorm-z** [comment]
> 我看了一下文档说查看是否同步完成可以通过访问 “[http://127.0.0.1:3000/api”](http://127.0.0.1:3000/api%E2%80%9D) 查看，但我执行了“curl [http://127.0.0.1:3000/api”](http://127.0.0.1:3000/api%E2%80%9D) 返回结果如下： {"code":0,"msg":"OK","data":{"trackerBlockHeight":null,"nodeBlockHeight":null,"latestBlockHeight":null}}



> 我看了一下文档说查看是否同步完成可以通过访问 “[http://127.0.0.1:3000/api”](http://127.0.0.1:3000/api%E2%80%9D) 查看，但我执行了“curl [http://127.0.0.1:3000/api”](http://127.0.0.1:3000/api%E2%80%9D) 返回结果如下： {"code":0,"msg":"OK","data":{"trackerBlockHeight":null,"nodeBlockHeight":null,"latestBlockHeight":null}}



> 我看了一下文档说查看是否同步完成可以通过访问 “[http://127.0.0.1:3000/api”](http://127.0.0.1:3000/api%E2%80%9D) 查看，但我执行了“curl [http://127.0.0.1:3000/api”](http://127.0.0.1:3000/api%E2%80%9D) 返回结果如下： {"code":0,"msg":"OK","data":{"trackerBlockHeight":null,"nodeBlockHeight":null,"latestBlockHeight":null}}

+1。感觉是网络问题，你用的哪个地区的服务器

**Comment by MarkSSH** [comment]
> +1。感觉是网络问题，你用的哪个地区的服务器

好像不是网络的问题，我全部按照默认的执行现在就开始正常执行了，不知道为啥改了用户名和密码就不行了，可能还有哪个地方没改到？

**Comment by yutou123** [comment]
> > +1。感觉是网络问题，你用的哪个地区的服务器
> 
> 好像不是网络的问题，我全部按照默认的执行现在就开始正常执行了，不知道为啥改了用户名和密码就不行了，可能还有哪个地方没改到？

我也遇到这个问题了容器就启动不起来，说是端口被占用。我换端口也不行

**Comment by astorm-z** [comment]
> > +1。感觉是网络问题，你用的哪个地区的服务器
> 
> 好像不是网络的问题，我全部按照默认的执行现在就开始正常执行了，不知道为啥改了用户名和密码就不行了，可能还有哪个地方没改到？

应该是。我这里两台机，一台境内机器挂代理，就是跟你一模一样的问题。另一台硅谷的，就正常

**Comment by astorm-z** [comment]
> > > +1。感觉是网络问题，你用的哪个地区的服务器
> > 
> > 
> > 好像不是网络的问题，我全部按照默认的执行现在就开始正常执行了，不知道为啥改了用户名和密码就不行了，可能还有哪个地方没改到？
> 
> 我也遇到这个问题了容器就启动不起来，说是端口被占用。我换端口也不行

tracker服务都端口冲突吗？这个服务默认占用3000端口。你可以看看3000端口被谁占用着，kill掉它

**Comment by MarkSSH** [comment]
> > > +1。感觉是网络问题，你用的哪个地区的服务器
> > 
> > 
> > 好像不是网络的问题，我全部按照默认的执行现在就开始正常执行了，不知道为啥改了用户名和密码就不行了，可能还有哪个地方没改到？
> 
> 应该是。我这里两台机，一台境内机器挂代理，就是跟你一模一样的问题。另一台硅谷的，就正常

我就一台境外的，之前境内代理挂不上，现在都默认就正常了，但是为什么我改了用户名密码就不行了，不清楚，希望 @opcatbugcloser 帮忙解答一下，非常感谢！

**Comment by astorm-z** [comment]
> > > > +1。感觉是网络问题，你用的哪个地区的服务器
> > > 
> > > 
> > > 好像不是网络的问题，我全部按照默认的执行现在就开始正常执行了，不知道为啥改了用户名和密码就不行了，可能还有哪个地方没改到？
> > 
> > 
> > 应该是。我这里两台机，一台境内机器挂代理，就是跟你一模一样的问题。另一台硅谷的，就正常
> 
> 我就一台境外的，之前境内代理挂不上，现在都默认就正常了，但是为什么我改了用户名密码就不行了，不清楚，希望 @opcatbugcloser 帮忙解答一下，非常感谢！

不好意思，我错了。确实是自定义了用户名密码才有问题

**Comment by kejunter** [comment]
> > > > > +1。感觉是网络问题，你用的哪个地区的服务器
> > > > 
> > > > 
> > > > 好像不是网络的问题，我全部按照默认的执行现在就开始正常执行了，不知道为啥改了用户名和密码就不行了，可能还有哪个地方没改到？
> > > 
> > > 
> > > 应该是。我这里两台机，一台境内机器挂代理，就是跟你一模一样的问题。另一台硅谷的，就正常
> > 
> > 
> > 我就一台境外的，之前境内代理挂不上，现在都默认就正常了，但是为什么我改了用户名密码就不行了，不清楚，希望 @opcatbugcloser 帮忙解答一下，非常感谢！
> 
> 不好意思，我错了。确实是自定义了用户名密码才有问题

你的问题解决了吗？

**Comment by xuelink** [comment]
<img width="1313" alt="Screenshot 2024-09-11 at 1 15 02 PM" src="https://github.com/user-attachments/assets/52fa5cc2-7595-45e9-97ba-74b13795cb07">

ubuntu-s-1vcpu-2gb-70gb-intel-nyc1-01 ? it is located in USA but still the same error.

**Comment by MarkSSH** [comment]
> <img alt="Screenshot 2024-09-11 at 1 15 02 PM" width="1313" src="https://private-user-images.githubusercontent.com/3280475/366411141-52fa5cc2-7595-45e9-97ba-74b13795cb07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNTAzNzYsIm5iZiI6MTcyNjA1MDA3NiwicGF0aCI6Ii8zMjgwNDc1LzM2NjQxMTE0MS01MmZhNWNjMi03NTk1LTQ1ZTktOTdiYS03NGIxMzc5NWNiMDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTFUMTAyMTE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDJlMmVkNDIyNjQ3ODE4ZjEwYTAwNTQ4OTUwMDc3MGQ5YjQxZmRmMWJlYmNjYmZkNmE2OGUzNWFiOGY0NjEzNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KLVfec0MMW6ifpgIDdBI7x9R1Cql7pkRRZL_Je6z1jo">
> ubuntu-s-1vcpu-2gb-70gb-intel-nyc1-01 ? it is located in USA but still the same error.

I'm having a different problem than you, so you might want to ask  @opcatbugcloser about that.

**Comment by MarkSSH** [comment]
> Tracker rpc config error

可以麻烦您说明一下如何自定义用户名和密码才能不导致这样的错误，谢谢！

**Comment by astorm-z** [comment]
> > > > > > +1。感觉是网络问题，你用的哪个地区的服务器
> > > > > 
> > > > > 
> > > > > 好像不是网络的问题，我全部按照默认的执行现在就开始正常执行了，不知道为啥改了用户名和密码就不行了，可能还有哪个地方没改到？
> > > > 
> > > > 
> > > > 应该是。我这里两台机，一台境内机器挂代理，就是跟你一模一样的问题。另一台硅谷的，就正常
> > > 
> > > 
> > > 我就一台境外的，之前境内代理挂不上，现在都默认就正常了，但是为什么我改了用户名密码就不行了，不清楚，希望 @opcatbugcloser 帮忙解答一下，非常感谢！  
> > 
> > 
> > 不好意思，我错了。确实是自定义了用户名密码才有问题
> 
> 你的问题解决了吗？

解决了，不要自定义账号和密码就好

**Comment by ShiSheng** [comment]
> > 我看了一下文档说查看是否同步完成可以通过访问 “[http://127.0.0.1:3000/api”](http://127.0.0.1:3000/api%E2%80%9D) 查看，但我执行了“curl [http://127.0.0.1:3000/api”](http://127.0.0.1:3000/api%E2%80%9D) 返回结果如下： {"code":0,"msg":"OK","data":{"trackerBlockHeight":null,"nodeBlockHeight":null,"latestBlockHeight":null}}
> 
> > 我看了一下文档说查看是否同步完成可以通过访问 “[http://127.0.0.1:3000/api”](http://127.0.0.1:3000/api%E2%80%9D) 查看，但我执行了“curl [http://127.0.0.1:3000/api”](http://127.0.0.1:3000/api%E2%80%9D) 返回结果如下： {"code":0,"msg":"OK","data":{"trackerBlockHeight":null,"nodeBlockHeight":null,"latestBlockHeight":null}}
> 
> > 我看了一下文档说查看是否同步完成可以通过访问 “[http://127.0.0.1:3000/api”](http://127.0.0.1:3000/api%E2%80%9D) 查看，但我执行了“curl [http://127.0.0.1:3000/api”](http://127.0.0.1:3000/api%E2%80%9D) 返回结果如下： {"code":0,"msg":"OK","data":{"trackerBlockHeight":null,"nodeBlockHeight":null,"latestBlockHeight":null}}
> 
> +1。感觉是网络问题，你用的哪个地区的服务器

@astorm-z 我也是这样的，no token，请问咋解决的呢

**Comment by cyberknight01** [comment]
你好我在执行  sudo yarn cli wallet create
报错如下 
exporting address to the RPC node ... 
rpc_create_watchonly_wallet failed!
request to http://127.0.0.1:8332/ failed, reason: socket hang up
是什么原因，没有任何变动配置
