### ISSUE TITLE
mint  question

### ISSUE THREAD

**Issue by codersimon6** [CATProtocol/cat-token-box#120]
The number of minted tokens exceeds the limit!

why？

**Comment by blacktux88** [comment]
same problem here

$ node dist/main mint -i c468e99ac3b533e503eac5ccf4f0e3362772f80cead8b7f71d802305d02f73d0_0 50
The number of minted tokens exceeds the limit!
Done in 22.07s.
root@node:/home/node/cat-token-box/packages/cli#

**Comment by justswash** [comment]
> same problem here
> 
> $ node dist/main mint -i c468e99ac3b533e503eac5ccf4f0e3362772f80cead8b7f71d802305d02f73d0_0 50 The number of minted tokens exceeds the limit! Done in 22.07s. root@node:/home/node/cat-token-box/packages/cli#

Remove the limit and mint like this:

mint -i c468e99ac3b533e503eac5ccf4f0e3362772f80cead8b7f71d802305d02f73d0_0
