### ISSUE TITLE
Send FB from the node

### ISSUE THREAD

**Issue by justswash** [CATProtocol/cat-token-box#122]
How do you send FB from within the node to another wallet?

**Comment by shizz-x** [comment]
you can print your wallet end export to unisat or something else, 

under packages/cli run 
```bash
cat wallet.json
```

**Comment by justswash** [comment]
> you can print your wallet end export to unisat or something else,
> 
> under packages/cli run
> 
> ```shell
> cat wallet.json
> ```

Yes that I can do. But I have a rare issue with one of the wallet where the seed generated does not reflect the same address after import. Im baffaled how this can even happen as I have does this over 100 times. So now I have FB stuck that I cant get out, unless theres a command in the node to transfer it.
