### ISSUE TITLE
How to disbale Merge trascation

### ISSUE THREAD

**Issue by ypdeveloper** [CATProtocol/cat-token-box#124]
Can anyone please help me out How I can disable merge trascation during every mint
there is already an issue cretaed with same topic but no clear anwser found there so I am creating it again and I am exprecting a proper soloutin as merge trascation cost alot

**Comment by justswash** [comment]
In cat-token-box/packages/cli/src/commands/mint/mint.command.ts

In the file remove or comment out the line below (line 89)
await this.merge(token, address);

Then when fees are very low, make a transfer manually to merge the tokens
