### ISSUE TITLE
Issue: Remaining Supply 校验问题 / Remaining Supply Validation Issue

### ISSUE THREAD

**Issue by Sharp-Lee** [CATProtocol/cat-token-box#125]
#### 描述 / Description

在当前的 OpenMinter V2 协议实现中，用户可以通过修改代码逻辑，返回空的 `splitAmountList`，导致某些 minter 还有剩余铸造量但没有创建新的 minter。这可能会导致剩余的铸造量无法被使用，影响代币的总供应量管理。

In the current implementation of the OpenMinter V2 protocol, users can modify the code logic to return an empty `splitAmountList`, resulting in some minters having remaining minting capacity but no new minters being created. This can lead to the remaining minting capacity being unusable, affecting the total supply management of the token.

#### 重现步骤 / Steps to Reproduce

1. 创建一个新的 OpenMinter V2 合约，并设置初始铸造量和限制。
2. 进行多次铸造操作，确保每次铸造后剩余的铸造量小于限制。
3. 在某次铸造操作中，用户修改代码逻辑，使 `getSplitAmountList` 返回空的 `splitAmountList`。
4. 观察到当前 minter 还有剩余铸造量，但没有创建新的 minter。

 .
1. Create a new OpenMinter V2 contract and set the initial minting amount and limits.
2. Perform multiple minting operations, ensuring that the remaining minting capacity is less than the limit after each operation.
3. In one of the minting operations, modify the code logic to make `getSplitAmountList` return an empty `splitAmountList`.
4. Observe that the current minter still has remaining minting capacity, but no new minter is created.

#### 预期行为 / Expected Behavior

1. 协议层应该对每个 minter 的剩余铸造量进行校验，确保在有剩余铸造量的情况下，必须创建新的 minter，以便所有剩余的铸造量都能被使用。
6. 如果没有创建新的 minter 的交易应该被视为无效和不合法。

1. The protocol layer should validate the remaining minting capacity of each minter, ensuring that new minters must be created when there is remaining minting capacity so that all remaining capacity can be used.
2. Transactions that do not create new minters should be considered invalid and illegal.

#### 实际行为 / Actual Behavior

用户可以通过修改代码逻辑，使 `getSplitAmountList` 返回空的 `splitAmountList`，导致某些 minter 还有剩余铸造量但没有创建新的 minter。这会导致剩余的铸造量无法被使用。

Users can modify the code logic to make `getSplitAmountList` return an empty `splitAmountList`, resulting in some minters having remaining minting capacity but no new minters being created. This leads to the remaining minting capacity being unusable.

#### 建议的解决方案 / Suggested Solution

在协议层添加对 `Remaining Supply` 的校验逻辑，确保在有剩余铸造量的情况下，必须创建新的 minter。如果没有创建新的 minter 的交易应该被视为无效和不合法。

Add validation logic for `Remaining Supply` at the protocol layer to ensure that new minters must be created when there is remaining minting capacity. Transactions that do not create new minters should be considered invalid and illegal.

**Comment by opcatdev** [comment]
openMinter v2 doesn't have this kind of issue
