### ISSUE TITLE
 mint token [CAT20_PIZZA] failed

### ISSUE THREAD

**Issue by jasonpmj** [CATProtocol/cat-token-box#127]
yarn run v1.22.21
$ node dist/main mint -i 59d566844f434e419bf5b21b5c601745fcaaa24482b8d68f32b2582c61a95af2_0 10 --fee-rate 1100
retry to mint token [CAT20_PIZZA] ...
retry to mint token [CAT20_PIZZA] ...
retry to mint token [CAT20_PIZZA] ...
retry to mint token [CAT20_PIZZA] ...
retry to mint token [CAT20_PIZZA] ...
retry to mint token [CAT20_PIZZA] ...
retry to mint token [CAT20_PIZZA] ...
retry to mint token [CAT20_PIZZA] ...
retry to mint token [CAT20_PIZZA] ...
retry to mint token [CAT20_PIZZA] ...
mint token [CAT20_PIZZA] failed
✨  Done in 148.53s.

请问这是什么问题，一直出错，已经git pull 了，还是这样

**Comment by crypt0biwan** [comment]
is your tracker synced 100%?

**Comment by jasonpmj** [comment]
No, but the synchronized block has exceeded the deployed block. If it is not the deployed block, it will prompt no token

**Comment by opcatdev** [comment]
sync up tracker first
