### ISSUE TITLE
Insufficient satoshis balance!

### ISSUE THREAD

**Issue by jasonpmj** [CATProtocol/cat-token-box#129]
$ node dist/main mint -i 5f0269c103284485964d8db6468502eff8a689febba47ecae91e5a813a4e50a9_0
Insufficient satoshis balance!
Insufficient satoshis balance!

I used 2 addresses with sufficient balances, but got the same message. What's the problem?

**Comment by raduciobanu22** [comment]
Similar issue here when trying to send tokens

**Comment by catdev2024** [comment]
try to make sure your wallet is loaded in the rpc node
