### ISSUE TITLE
Merge failed & mint failed

### ISSUE THREAD

**Issue by LOGFATAL** [CATProtocol/cat-token-box#13]
![微信图片_20240911164115](https://github.com/user-attachments/assets/21c60149-4f15-4ed8-9e83-75385d723bc3)
![微信图片_20240911164120](https://github.com/user-attachments/assets/5a6cc3e6-2586-4809-8bce-6c46f8310503)

**Comment by opcatbugcloser** [comment]
Tracker need to be running properly and synchronized

**Comment by LOGFATAL** [comment]
What am I supposed to do?

> Tracker need to be running properly and synchronized
