### ISSUE TITLE
Some people modify the code to only consume minters without generating new ones.

### ISSUE THREAD

**Issue by flipCatDoge** [CATProtocol/cat-token-box#132]
Nowadays, there are quite a few selfish individuals who, in order to save a few percent on gas fees, have tampered with the code. This has resulted in each transaction consuming one minter without generating a new one. 
I hope everyone will work together to maintain the community ecosystem! 
I believe certain behaviors must be constrained by the constitution, and I hope future protocols can reasonably address this issue.

**Comment by xhliu** [comment]
Use open mint V2 https://x.com/ProtocolCAT/status/1835534033083826573

**Comment by CATProtocol** [comment]
Use open mint V2 https://x.com/ProtocolCAT/status/1835534033083826573
