### ISSUE TITLE
Tracker Scync very slow

### ISSUE THREAD

**Issue by gokhaneryigit** [CATProtocol/cat-token-box#133]
How many hours does it normally take to complete the sync?
It's been open for hours and it's only 17%. Also, it seems like the difference with the total number of blocks will never close. Is there a way to download in bulk?
![image](https://github.com/user-attachments/assets/5cf298f9-8927-4cfe-b168-488b97a775eb)

also from 
http://127.0.0.1:3000/api
![image](https://github.com/user-attachments/assets/99acc830-b5e3-4103-ba82-770fb3ab1fbd)

**Comment by easyranger** [comment]
I have a similar problem...

It seems that tracker block is not synchronizing as fast as latest block is growing....

**Comment by gokhaneryigit** [comment]
> I have a similar problem...
> 
> It seems that tracker block is not synchronizing as fast as latest block is growing....

yes it seems

**Comment by Nodejssx** [comment]
I can upload my snapshot to your server for 10 FB.
