### ISSUE TITLE
是不是要Mint需要等这个nodeBlockHeight和latestBlockHeight一致啊

### ISSUE THREAD

**Issue by 274335390** [CATProtocol/cat-token-box#138]
{"code":0,"msg":"OK","data":{"trackerBlockHeight":7502,"nodeBlockHeight":18955,"latestBlockHeight":51584}}

**Comment by ithedeployer** [comment]
是的，根据我的经验至少80%

**Comment by Nodejssx** [comment]
I can upload my snapshot to your server for 10 cat.

**Comment by njskyun** [comment]
没有强制要求高度，只是要求minter来帮我筑币，但是你高度要是低的话，大概率minter早被人抢跑了，你再拿去mint节点那边就会报输入（input）已经被用了

**Comment by 274335390** [comment]
> 没有强制要求高度，只是要求minter来帮我筑币，但是你高度要是低的话，大概率minter早被人抢跑了，你再拿去mint节点旁边就会报输入（input）已经被用了

{"code":0,"msg":"OK","data":{"trackerBlockHeight":10362,"nodeBlockHeight":54696,"latestBlockHeight":54696}}
大神，再问问，我现在这个nodeBlockHeight是同步完成了，但是trackerBlockHeight还差的远，
我现在执行yarn cli wallet balances，结果是：
tracker is behind latest blockchain height
processing 10355/54689: 19%

1、现在执行mint，然后去找tokenId（我在https://explorer.unisat.io/fractal-mainnet/cat20下找的），有些是直接找不到，是不是要等这个trackerBlockHeight也和latestBlockHeight一致，才能算完全同步成功啊？
2、有没有其他办法加快这个trackerBlockHeight的速度？

**Comment by opcatdev** [comment]
https://github.com/CATProtocol/cat-token-box/blob/main/packages/tracker/README.md

![CleanShot-20240927214746](https://github.com/user-attachments/assets/fb109e6e-1733-4f9f-9d55-56b2a75f35ef)
