### ISSUE TITLE
"sudo yarn build" removes the artifact files before built and thus cause error in building

### ISSUE THREAD

**Issue by crackeryo** [CATProtocol/cat-token-box#144]
I removed the line that cleans up the artifact and it finally built successfully. Any side effect for doing so?

**Comment by jiafu83** [comment]
> I removed the line that cleans up the artifact and it finally built successfully. Any side effect for doing so?

which line  that cleans up the artifact？ I got the same problem, also confused

**Comment by justswash** [comment]
same issue here
