### ISSUE TITLE
Using new method "yarn start:worker:prod" to sync the data instead of docker,"trackerBlockHeight" does not change...

### ISSUE THREAD

**Issue by easyranger** [CATProtocol/cat-token-box#146]
while using the new code updated 2 days ago.

Using new method "yarn start:worker:prod" to sync the data instead of docker,I found an issue: 

Only the "nodeBlockHeight" changes,and "trackerBlockHeight" does not change...

**Comment by opcatdev** [comment]
nodeBlockHeight changes means the fractal node is syncing, check worker logs to see whether the tracker is syncing

**Comment by easyranger** [comment]
> nodeBlockHeight changes means the fractal node is syncing, check worker logs to see whether the tracker is syncing

Following your comment,I have found something:
Using yarn start:worker:prod: the logs prompts right on console,which seems all right,but the trackerBlockHeight does not change
Using yarn start:worker in development mode,the trackerBlockHeight updated...

weird....

**Comment by opcatdev** [comment]
what's the log of running`yarn start:worker:prod`, sounds like it is not gonna happen, should something's not configured correctly.

**Comment by easyranger** [comment]
I just stop `start:worker` and try `yarn start:worker:prod` again...It works fine,and the trackerBlockHeight updated successfully....

Should be something wrong with configuration....

Thanks!By the way,the issue can be closed

![屏幕截图 2024-09-29 151000](https://github.com/user-attachments/assets/f9ab3bb8-f7cc-4894-88bd-7f0e01bdd563)
