### ISSUE TITLE
About the permission!

### ISSUE THREAD

**Issue by yadgen** [CATProtocol/cat-token-box#148]
I am operating on ubuntu22 system, why do I need to add sudo to run these two commands?
`yarn start:api:prod`
`yarn start:worker:prod`

**Comment by easyranger** [comment]
When worker sync the data,the api can help you to see the sync progress on web browser

**Comment by yadgen** [comment]
> When the worker:prod sync the data,the api:prod can help you to see the sync progress on the web browser

I still can't understand why I need root privileges, since all my other services are started as normal users.

**Comment by easyranger** [comment]
If you are sure there are no problems, you can certainly run the programs as normal user rather than root....
