### ISSUE TITLE
success output txid

### ISSUE THREAD

**Issue by seanng123456789** [CATProtocol/cat-token-box#149]
Dear Team,

I am synced all the tracker and fractal bitcoin, once minted, the message of success mint display as "Minting 202.00 NYAN tokens in txid: 98c9b5929a9f2ddd47b85e5f2a2d3501b59a4e1edafc6a4e968259ef5ab32a49 ...", however, the txid hasn't appear in the mempool after a plenty of time. It seems to me that it never boardcasted. I m not familiar with this kind of script, so would you please help me to debug or tell me how to check these kind of stuffs

Regards
Sean

**Comment by ThreeAndTwo** [comment]
You should check your BTC full node; it is not related to this protocol.

**Comment by opcatdev** [comment]
Transactions might be pruned by mempool depending on the network load.
