### ISSUE TITLE
ERROR [RpcService] rpc error, Request failed with status code 503, {"jsonrpc":"1.0","id":1726048398876,"method":"getblockchaininfo","params":[]}

### ISSUE THREAD

**Issue by TheHeBoy** [CATProtocol/cat-token-box#15]
how to solve the issue with tracker ?

**Comment by opcatbugcloser** [comment]
<img width="1128" alt="image" src="https://github.com/user-attachments/assets/6340700f-99d8-4707-96fb-16c4ba759492">

**Comment by opcatbugcloser** [comment]
Start tracker dependency

**Comment by W-Y-P** [comment]
> [opcatbugcloser](/opcatbugcloser)

#25  not solved, what does this mean?
