### ISSUE TITLE
这日志算是正常？

### ISSUE THREAD

**Issue by Li-Ace** [CATProtocol/cat-token-box#155]
[Nest] 15780  - 2024/10/02 22:52:37   ERROR [TxService] process tx 8bdc985b3f643e6d19c6e1628251044f8e0e45270ddd6123b962add09561d927 error, 字段 TokenInfoEntity.first_mint_height 不存在     
[Nest] 15780  - 2024/10/02 22:52:37   ERROR [TxService] process tx fa948c05dd4d6efa09f5cc3dd8b3057322c25da6484496b5dd3d56f2c63ccb48 error, 字段 TokenInfoEntity.first_mint_height 不存在     
[Nest] 15780  - 2024/10/02 22:52:37   ERROR [TxService] process tx 145dbd149d05f140334ab17d1daffcdbb37ddca7965ed91e2f7f5e5808fb8fa2 error, 字段 TokenInfoEntity.first_mint_height 不存在     
[Nest] 15780  - 2024/10/02 22:52:37   ERROR [TxService] process tx b9e7886c1d0845680cf565e385b7861d6d309fc460b1bf034e39afd7880c2a06 error, 字段 TokenInfoEntity.first_mint_height 不存在     
[Nest] 15780  - 2024/10/02 22:52:37   ERROR [TxService] process tx fe9de218a570d7e69464e10c68d2b19e1fdb709e651518cbac20c1ca33309983 error, 字段 TokenInfoEntity.first_mint_height 不存在     
[Nest] 15780  - 2024/10/02 22:52:37   ERROR [TxService] process tx 8f316d1d38d1dc0a208090dca211e4958729521c9e29f2bc144b93f063016385 error, 字段 TokenInfoEntity.first_mint_height 不存在     
[Nest] 15780  - 2024/10/02 22:52:37   ERROR [TxService] process tx bfd7f27d09b500558ded617e6c54fedeed332cf422f96c8a610a7928d9958fad error, 字段 TokenInfoEntity.first_mint_height 不存在     
[Nest] 15780  - 2024/10/02 22:52:37   ERROR [TxService] process tx 4b1c9d47e2c85f25896d8d46ab842dbb6f8c06870ddcdfc506c01abd550f0500 error, 字段 TokenInfoEntity.first_mint_height 不存在  

![image](https://github.com/user-attachments/assets/b33f34e2-5c6e-439b-93bf-86b2c56dfc91)

**Comment by opcatdev** [comment]
run migration first https://github.com/CATProtocol/cat-token-box/blob/main/packages/tracker/README.md#migration

**Comment by Li-Ace** [comment]
> run migration first https://github.com/CATProtocol/cat-token-box/blob/main/packages/tracker/README.md#migration-----------谷歌翻译-----------首先运行迁移

already run it, it seems did not work
