### ISSUE TITLE
Unable to run tracker

### ISSUE THREAD

**Issue by yes168** [CATProtocol/cat-token-box#156]
~/cat-token-box# docker logs tracker yarn run v1.22.22 error Command "start:prod" not found. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by hcxiong** [comment]
这个问题依然存在.

**Comment by opcatdev** [comment]
https://github.com/CATProtocol/cat-token-box/blob/main/packages/tracker/README.md#run
```
yarn start:worker:prod
yarn start:api:prod
```
