### ISSUE TITLE
Address is different between cat-token-box and Unisat

### ISSUE THREAD

**Issue by dbarobin** [CATProtocol/cat-token-box#16]
I notice the path is the same with the Unisat with this [commit](https://github.com/CATProtocol/cat-token-box/commit/cb0a7e382ef9defb8a2477eb3b116c029ae03a09), but I generate the mnemonic from the old code, and I import the mnemonic to the Unisat and custom hd path at `m/44'/0'/0'/0/0`. Unfortunately, the Taproot address in Unisat is not the same as the code generated even in the custom hd path.

How do I solve this issue? Thanks.

**Comment by opcatbugcloser** [comment]
<img width="341" alt="image" src="https://github.com/user-attachments/assets/f2ec0e3d-2d42-49eb-a5a2-bcccc40d236f">

m/44'/0'/0'/0/0 and select p2tr address type

We fixed at cb0a7e382ef9defb8a2477eb3b116c029ae03a09
