### ISSUE TITLE
exporting address to the RPC node ...  rpc_create_watchonly_wallet failed! request to http://127.0.0.1:8332/ failed, reason: socket hang up

### ISSUE THREAD

**Issue by gviiisen** [CATProtocol/cat-token-box#17]
exporting address to the RPC node ... 
rpc_create_watchonly_wallet failed!
request to http://127.0.0.1:8332/ failed, reason: socket hang up

**Comment by opcatbugcloser** [comment]
Start the node and try again

**Comment by 1035875857** [comment]
I have also encountered the same problem. Do you have a solution

**Comment by 1035875857** [comment]
exporting address to the RPC node ...
rpc_create_watchonly_wallet failed!
Unauthorized

**Comment by opcatbugcloser** [comment]
Update rpc username and password.
```json
{
      "url": "http://127.0.0.1:8332",
      "username": "bitcoin",
      "password": "opcatAwesome"
}
```
