### ISSUE TITLE
Can't mint , stuck in merging ...

### ISSUE THREAD

**Issue by 0Xmorgan888** [CATProtocol/cat-token-box#19]
$ node dist/main mint -i 45ee725c2c5993b3e4d308842d87e973bf1951f5f7a804b21e4dd964ecd12d6b_0 5 --fee-rate 950
Start merging your [CAT] tokens ...
Spliting fee in txid: 5d62f047c60adbcfd80d91da016a48aa8c12467feeddb6d477ef36b526230ac3
Waiting tx: 5d62f047c60adbcfd80d91da016a48aa8c12467feeddb6d477ef36b526230ac3 to be confirmed ...

but there is no tx in mempool : 5d62f047c60adbcfd80d91da016a48aa8c12467feeddb6d477ef36b526230ac3 

ant each time i run the mint command it show different tx

**Comment by opcatbugcloser** [comment]
Wait for the address to confirm the transaction and try again

**Comment by 0Xmorgan888** [comment]
> Wait for the address to confirm the transaction and try again

The transaction not broadcasted , how it can be confirmed when it is not broadcasted ?
how log it take to broadcast ? 
and i have no tx uncofirmed in my wallet

**Comment by opcatbugcloser** [comment]
> node dist/main mint -i 45ee725c2c5993b3e4d308842d87e973bf1951f5f7a804b21e4dd964ecd12d6b_0 5 --fee-rate 950 Start merging your [CAT] tokens ... Spliting fee in txid: 5d62f047c60adbcfd80d91da016a48aa8c12467feeddb6d477ef36b526230ac3 Waiting tx: 5d62f047c60adbcfd80d91da016a48aa8c12467feeddb6d477ef36b526230ac3 to be confirmed ...
> 
> but there is no tx in mempool : 5d62f047c60adbcfd80d91da016a48aa8c12467feeddb6d477ef36b526230ac3
> 
> ant each time i run the mint command it show different tx

Sorry, the problem is that the node memory pool is full. Please wait until the node blocks out before continuing

**Comment by 0Xmorgan888** [comment]
> > node dist/main mint -i 45ee725c2c5993b3e4d308842d87e973bf1951f5f7a804b21e4dd964ecd12d6b_0 5 --fee-rate 950 Start merging your [CAT] tokens ... Spliting fee in txid: 5d62f047c60adbcfd80d91da016a48aa8c12467feeddb6d477ef36b526230ac3 Waiting tx: 5d62f047c60adbcfd80d91da016a48aa8c12467feeddb6d477ef36b526230ac3 to be confirmed ...
> > but there is no tx in mempool : 5d62f047c60adbcfd80d91da016a48aa8c12467feeddb6d477ef36b526230ac3
> > ant each time i run the mint command it show different tx
> 
> Sorry, the problem is that the node memory pool is full. Please wait until the node blocks out before continuing

is there any other way to do this ? 
i want to broadcast my transactions
