### ISSUE TITLE
助记词无法真确指向钱包

### ISSUE THREAD

**Issue by carl-2023** [CATProtocol/cat-token-box#20]
![1726067852878](https://github.com/user-attachments/assets/6c1663eb-cdb9-4c1f-9cff-3c7a64af90d9)
![1726067900853](https://github.com/user-attachments/assets/8136a833-ecb6-4772-b508-a7f109376b91)

**Comment by opcatbugcloser** [comment]
<img width="367" alt="image" src="https://github.com/user-attachments/assets/7a2bbebc-b646-4873-8dff-013290546cf9">
Select other wallet

**Comment by opcatbugcloser** [comment]
#8

**Comment by carl-2023** [comment]
![1726105294715](https://github.com/user-attachments/assets/f7733d59-193e-4420-90e5-0864263aa695)
<img width="529" alt="image" src="https://github.com/user-attachments/assets/7b6ae85b-bfff-4c55-a92f-6fc01b8c1873">
选择的这个钱包，选填项填的这个，还是不行，地址不对应

**Comment by llqllq1024** [comment]
自定义路径的时候最后一个/0不用填，他会自动补的， phrase 也不用填
