### ISSUE TITLE
yarn cli wallet balances，No tokens found!

### ISSUE THREAD

**Issue by zwancc** [CATProtocol/cat-token-box#21]
yarn cli wallet create success, and  yarn cli wallet address，Correctly return the wallet address, Deposit 1FB into the wallet, 

Show token balances
# yarn cli wallet balances
yarn run v1.22.22
$ node dist/main wallet balances
No tokens found!
Done in 1.82s.

![image](https://github.com/user-attachments/assets/9ff5e507-9937-456a-9d6f-6efcb74b9b5b)

What's the reason? How to solve it

**Comment by opcatbugcloser** [comment]
Wait tracker synced

**Comment by zwancc** [comment]
tracker already synced, 
![ddf19594f449b1b713b5d8c09ce5340](https://github.com/user-attachments/assets/014c3006-14ca-4bcc-a7a7-b6b0debb2955)

**Comment by chenxi2015** [comment]
I have the same question. It still doesn't work after several hours.

**Comment by yappy876** [comment]
how do u fix this ??

**Comment by somethingbeta** [comment]
this doesnt show you your FB balance when you run wallet balances ...

**Comment by zwancc** [comment]
yarn cli wallet address ，Only display your balance after successfully minting，
like this:
![6556a44a8408253133b989c24b7dc3f](https://github.com/user-attachments/assets/40cb7bf1-32c3-4ef7-a3fe-6cf688218aaa)

**Comment by zwancc** [comment]
The document misled us. The process should be: 1. recharge fb coin  2. Mint,   3. Run "yarn cli wallet balances " to check the balances

**Comment by gokhaneryigit** [comment]
> Wait tracker synced

hi , sync is very slow. It's been open for hours and it's only 17%. Also, it looks like the gap with the total number of blocks will never close. Is there a way to download in bulk?
