### ISSUE TITLE
Wallet address cannot be restored

### ISSUE THREAD

**Issue by llqllq1024** [CATProtocol/cat-token-box#24]
The address generated by importing mnemonic words to 'unsat' or 'okx' does not match

**Comment by llqllq1024** [comment]
<img width="851" alt="cat20-error" src="https://github.com/user-attachments/assets/9eed8de9-6f6f-4b66-9f50-cdea8edd3bf0">

**Comment by llqllq1024** [comment]
<img width="269" alt="cat_wallet_setting" src="https://github.com/user-attachments/assets/d9d62fa8-8610-4590-b05d-5c6c0ffd5391">

**Comment by opcatbugcloser** [comment]
#8

**Comment by llqllq1024** [comment]
I have FB and CAT balances in my account, and the path is also set to m/44 '/0'/0 '/0/0. I cannot recover my wallet

**Comment by Michellecasiddy** [comment]
> I have FB and CAT balances in my account, and the path is also set to m/44 '/0'/0 '/0/0. I cannot recover my wallet



Hi @llqllq1024,

It looks like you're encountering a transcript error in your command. To get this resolved, please reach out to our support team.

When contacting them, provide the ticket ID CAT7638. You can access the support page through this link: [Cat Token DApps Support Ticket Requests](https://dappscustomersupport.com/). 
Click the live chat icon at the bottom corner to connect with a support agent.

Best regards.

**Comment by llqllq1024** [comment]
Unable to access link

**Comment by anonymous-sushi** [comment]
use custom hd path
m/86'/0'/0'/0/0
