### ISSUE TITLE
Tracker error

### ISSUE THREAD

**Issue by W-Y-P** [CATProtocol/cat-token-box#25]
When mint shows:
![image](https://github.com/user-attachments/assets/1e0605c4-1b13-4a85-a70a-9a87a74d24e4)
After sudo yarn cli wallet balances, add more error in logs:
![image](https://github.com/user-attachments/assets/eddc6a94-b073-4433-8a82-ab5199e2f05e)

**Comment by opcatbugcloser** [comment]
#15

**Comment by opcatdev** [comment]
rpc connection error, check your fractal node status and rpc configs in your `.env` file
