### ISSUE TITLE
Disable merging

### ISSUE THREAD

**Issue by lifofifoX** [CATProtocol/cat-token-box#29]
Are there any downside to avoid merging UTXOs when minting a CAT20 token? Would it affect minting in any way?

**Comment by 0Xmorgan888** [comment]
same problem

**Comment by xiangpengm** [comment]
The essence of the merge is to help users maintain the utxo collection, so that users have a better experience in the subsequent use of the process, closing the merge does not affect the minting, but will produce a lot of small utxo, the future transfer needs to merge

**Comment by opcatbugcloser** [comment]
The essence of the merger is to help users maintain the utxo collection, so that users have a better experience in the subsequent use of the process, closing the merger does not affect the minting, but will produce a lot of small utxo, the future transfer needs to merge

**Comment by lifofifoX** [comment]
@opcatbugcloser Thank you for clarifying!

Right now, merging is very expensive because of high fee rate of 1500+ sat/vB. So, avoiding merging when minting saves a lot of money.

**Comment by opcatbugcloser** [comment]
You can use other fork code that has been modified to close the merge, such as https://github.com/ThreeAndTwo/cat-token-box/commits/main/ , or modify the code yourself to remove the merge
