### ISSUE TITLE
Invalid Argument: Output satoshis is not a natural number

### ISSUE THREAD

**Issue by mtezy** [CATProtocol/cat-token-box#30]
Start merging your [CAT] tokens ...
Insufficient satoshis balance!
mint failed!
Invalid Argument: Output satoshis is not a natural number
Done in 1.14s.

**Comment by xueyuchen** [comment]
the same error, how to fix it?

**Comment by mtezy** [comment]
solved with rebooting machine

**Comment by mtezy** [comment]
> the same error, how to fix it?

reboot machine. 
# stop docker tracker
``docker stop tracker``
# Start stracker
``docker start tracker``

**Comment by xueyuchen** [comment]
I will rent a new machine, reconfigure the nodes, and use a new wallet，it show the same error

**Comment by abu3389** [comment]
> have you try rebooting prev. machine? it worked for me
 rebooting and stop/start tracker not work ,get same message 
 
Insufficient satoshis balance!
mint failed!
Invalid Argument: Output satoshis is not a natural number

**Comment by eminentgu** [comment]
Reboot and restart docker doesn't work for me. I tried to reproduce  by doing curl -X POST http://127.0.0.1:8332/wallet/cat-910b90fe \
     -H "Content-Type: application/json" \
     -H "Authorization: Basic Yml0Y29pbjpvcGNhdEF3ZXNvbWU=" \
     -d '{"jsonrpc":"2.0","id":"cat-cli","method":"listunspent","params":[0,9999999,["My wallet Address"]}' and it returned

**Comment by anonymous-sushi** [comment]
out of sync tracker

**Comment by opcatdev** [comment]
#22
