### ISSUE TITLE
Start merging your [CAT] tokens ...Invalid Argument: Output satoshis is not a natural number

### ISSUE THREAD

**Issue by zhanghanke** [CATProtocol/cat-token-box#31]
$ node dist/main mint -i 45ee725c2c5993b3e4d308842d87e973bf1951f5f7a804b21e4dd964ecd12d6b_0 5
Start merging your [CAT] tokens ...
mint failed!
Invalid Argument: Output satoshis is not a natural number

I confirm that the balance is normal with 13 FB, and the 4-hour script is still normal

**Comment by mtezy** [comment]
[Solved](https://github.com/CATProtocol/cat-token-box/issues/30#issuecomment-2345054152)

**Comment by zhanghanke** [comment]
docker stop tracker
docker start tracker  

It didn't solve the problem

**Comment by zhanghanke** [comment]
[cli]$ docker stop tracker
tracker
[cli]$ docker start tracker
tracker
[cli]$ sudo yarn cli mint -i 45ee725c2c5993b3e4d308842d87e973bf1951f5f7a804b21e4dd964ecd12d6b_0 5
yarn run v1.22.22
$ node dist/main mint -i 45ee725c2c5993b3e4d308842d87e973bf1951f5f7a804b21e4dd964ecd12d6b_0 5
Start merging your [CAT] tokens ...
mint failed!
Invalid Argument: Output satoshis is not a natural number
Done in 1.04s.

**Comment by anonymous-sushi** [comment]
let your tracker catch up

**Comment by zhanghanke** [comment]
> catch up

What does catch up mean? upgrade

**Comment by opcatdev** [comment]
#22
