### ISSUE TITLE
yarn cli mint: broadcast_rpc failed!

### ISSUE THREAD

**Issue by zgwldrc** [CATProtocol/cat-token-box#32]
COMMANDLINE: 
$ yarn cli mint -i 45ee725c2c5993b3e4d308842d87e973bf1951f5f7a804b21e4dd964ecd12d6b_0 1

ERROR INFO:
get raw transaction accdd7f83f6c887399065dad022b7fd7327d2b5e450fbac5ffb09a3eaced99c4 failed!
{"result":null,"error":{"code":-5,"message":"No such mempool transaction. Use -txindex or provide a block hash to enable blockchain transaction queries. Use gettransaction for wallet transactions."},"id":"cat-cli"}
fetch minters failed, minter: bc1pqw9ncs4sna0ndh85ux5dhh9swueyjql23t4em8j0smywkqsngfmsn7gmua
fetch open minter state failed, minter: bc1pqw9ncs4sna0ndh85ux5dhh9swueyjql23t4em8j0smywkqsngfmsn7gmua, txId: accdd7f83f6c887399065dad022b7fd7327d2b5e450fbac5ffb09a3eaced99c4
mint token [CAT] failed

**Comment by zgwldrc** [comment]
this is my packages/cli/config.json
{
  "network": "fractal-mainnet",
  "tracker": "http://127.0.0.1:3000",
  "dataDir": ".",
  "maxFeeRate": 3,
  "rpc": {
      "url": "http://127.0.0.1:8332",
      "username": "bitcoin",
      "password": "xxxxx"
  }
}

**Comment by anonymous-sushi** [comment]
retry the tx
