### ISSUE TITLE
broadcast merge token txs failed

### ISSUE THREAD

**Issue by lionman888** [CATProtocol/cat-token-box#34]
mint failed!
broadcast merge token txs failed, {"result":null,"error":{"code":-26,"message":"txn-mempool-conflict"},"id":"cat-cli"}
这个应该怎么解决呢

**Comment by opcatbugcloser** [comment]
Wait for transaction confirmation and try again

**Comment by suifengpiao3210** [comment]
i have the same question today  do you resolve?
