### ISSUE TITLE
Insufficient satoshis balance!

### ISSUE THREAD

**Issue by bilbilmyc** [CATProtocol/cat-token-box#36]
yarn run v1.22.22
$ node dist/main mint -i 45ee725c2c5993b3e4d308842d87e973bf1951f5f7a804b21e4dd964ecd12d6b_0 5
Insufficient satoshis balance!
Insufficient satoshis balance!
Done in 1.18s.

![image](https://github.com/user-attachments/assets/0dbfc1df-a810-4bef-ba2d-98608073311c)
明明有一个FB，为什么报错余额不足

**Comment by opcatbugcloser** [comment]
There are two possibilities, the first is that the node is not synchronized, and the second is that the wallet created does not import the node correctly. The second point can be fixed by running the following instructions.
```bash
yarn cli wallet export
```

**Comment by ismailmoazami** [comment]
I have same issue, """yarn cli wallet export""" command did not solve issue, how much it takes to sync the node?

**Comment by pirateOfGit** [comment]
> There are two possibilities, the first is that the node is not synchronized, and the second is that the wallet created does not import the node correctly. The second point can be fixed by running the following instructions.
> 
> ```shell
> yarn cli wallet export
> ```

Any idea what causes this error ?

![image](https://github.com/user-attachments/assets/4596d370-4c78-40ec-bfa7-cbeb6078658d)

My tracker container also keeps exiting...

![image](https://github.com/user-attachments/assets/4e89a7e9-7fcb-44b1-85d3-ad674ac5b5f3)

**Comment by billyrestey** [comment]
Fix: Delete your cli wallet. Create new cli wallet. Make sure you get "successful" log when it connects with RPC.

**initial problem was created a cli wallet before the node/tracker were sync'd.

**Comment by yappy876** [comment]
i have the same issue

**Comment by pirateOfGit** [comment]
> Fix: Delete your cli wallet. Create new cli wallet. Make sure you get "successful" log when it connects with RPC.
> 
> **initial problem was created a cli wallet before the node/tracker were sync'd.

how do i stop my tracker from exiting ? i have this error now 

![image](https://github.com/user-attachments/assets/6dde29e4-2a96-4a8e-ac90-27582d04d272)

**Comment by bilbilmyc** [comment]
我可以了，删除钱包后 从新创建一个钱包能可以使用
