### ISSUE TITLE
同步完成后，执行一段时间报rpc error, maxContentLength size of -1 exceeded

### ISSUE THREAD

**Issue by astorm-z** [CATProtocol/cat-token-box#37]
![image](https://github.com/user-attachments/assets/9a1ba5d2-d462-4b14-8153-df9051440532)

已经同步100%了，执行一段时间后报 rpc error, maxContentLength size of -1 exceeded

服务器2核、4G。内存占用3222M左右，cpu峰值可达90+%。

现在是跑不动了吗

**Comment by opcatbugcloser** [comment]
The tracker will try again, please ignore

**Comment by astorm-z** [comment]
> The tracker will try again, please ignore

服务器有点卡死了，之前还很流畅。之后是不是2核服务器已经扛不住了

**Comment by opcatdev** [comment]
upsize the server, 8 CPUs and 16G RAM is recommended
