### ISSUE TITLE
,"nodeBlockHeight":null,"latestBlockHeight":null}}`

### ISSUE THREAD

**Issue by albe777-hash** [CATProtocol/cat-token-box#38]
`{"code":0,"msg":"OK","data":{"trackerBlockHeight":11118,"nodeBlockHeight":null,"latestBlockHeight":null}}`

was almost synced and then got this

**Comment by abu3389** [comment]
how fix it? i have same

**Comment by dqminh100** [comment]
how fix it? i have same issue
