### ISSUE TITLE
为了安全，应该增加如何修改数据库账号密码，已爆出漏洞被利用成矿机了

### ISSUE THREAD

**Issue by codewc** [CATProtocol/cat-token-box#44]
为了安全，应该增加如何修改数据库密码，已爆出漏洞被利用成矿机了。
我尝试修改了数据库配置文件，但是账号密码可能在其他地方有使用，修改后无法同步。所以建议文档增加这一部分内容

**Comment by a6b017** [comment]
cat-token-box/packages/tracker 下的env文件中的密码已修改 但还是在 PG 镜像中出现了挖矿病毒
