### ISSUE TITLE
tracker status is abnormal

### ISSUE THREAD

**Issue by Tanniks** [CATProtocol/cat-token-box#48]
![image](https://github.com/user-attachments/assets/76fcd10d-bdbb-409f-9743-d9712d416130)
I synced my data last night, but today I cannot get my balance. What happened?@opcatbugcloser

**Comment by Tanniks** [comment]
![image](https://github.com/user-attachments/assets/bbc550bd-0025-459b-a14c-4e0bc9d7dd2f)
Still have, can anyone help?

**Comment by opcatdev** [comment]
https://github.com/CATProtocol/cat-token-box/issues/134#issuecomment-2377677363
