### ISSUE TITLE
Postgres wide open to the public Internet with "postgres" as the password.

### ISSUE THREAD

**Issue by damianharouff** [CATProtocol/cat-token-box#49]
[The postgres container](https://github.com/CATProtocol/cat-token-box/blob/85f42f170137481abd8337d0417aad5956c1b88e/packages/tracker/docker-compose.yml) is open to the public Internet with default username and password of "postgres".

[This is the default env file ](https://github.com/CATProtocol/cat-token-box/blob/main/packages/tracker/.env.example)that is used for it:

```
DATABASE_TYPE=postgres
DATABASE_HOST=127.0.0.1
DATABASE_PORT=5432
DATABASE_DB=postgres
DATABASE_USERNAME=postgres
DATABASE_PASSWORD=postgres
```

Even though postgres is running on 127.0.0.1 inside the container, docker exposes the port publicly. And in combination with postgres:postgres as the username and pass, you can assume what is gonna happen.

Furthermore, I'm sure there's an expectation of changing the username and password, but with people blindly copy and pasting instructions without understanding what they're doing, it's getting left as postgres:postgres.

We've been getting hammered with endless notices that customer servers are compromised by attackers. 

Everyone who runs this is at risk of losing everything, because it's wide open to any adversary.

**Comment by xz888888** [comment]
Could you explain a bit how attackers can access the DB from outside? I don't understand the statement "docker exposes the port publicly".

**Comment by damianharouff** [comment]
People are installing it on servers connected to the public Internet.

**Comment by xz888888** [comment]
> People are installing it on servers connected to the public Internet.

A server that's not behind any kind of router/firewall ? That's like waiting for disasters to happen.

**Comment by damianharouff** [comment]
And yet the only disaster that ever happens is when obviously insecure passwords are used. My favorite is @123 at the end of a common word. Brute forcers will definitely never try that!

**Comment by opcatdev** [comment]
nice explanation

> Everyone who runs this is at risk of losing everything, because it's wide open to any adversary.

the word everything sounds too scary, they will lose the postgres container only, and the host server is safe by the way.
