### ISSUE TITLE
No token found for tokenId: 45ee725c2c5993b3e4d308842d87e973bf1951f5f7a804b21e4dd964ecd12d6b_0

### ISSUE THREAD

**Issue by luchuanqi** [CATProtocol/cat-token-box#5]
![image](https://github.com/user-attachments/assets/dca78cb1-ef0c-4187-bc92-76e4588d709b)

$ node dist/main mint -i 45ee725c2c5993b3e4d308842d87e973bf1951f5f7a804b21e4dd964ecd12d6b_0 5
No token found for tokenId: 45ee725c2c5993b3e4d308842d87e973bf1951f5f7a804b21e4dd964ecd12d6b_0
Done in 1.42s.
yarn run v1.22.22

**Comment by opcatbugcloser** [comment]
Please wait tracker synced

**Comment by ShiSheng** [comment]
> Please wait tracker synced

 how to check tracker sync status?

**Comment by opcatbugcloser** [comment]
> > Please wait tracker synced
> 
> how to check tracker sync status?


View the docker compose log

**Comment by Rickiiii** [comment]
my tracker synced ready like this
![image](https://github.com/user-attachments/assets/501f4f7a-d70d-4737-9511-01b068e4394b)

but i still do not have tokens.json file

when this file generate

**Comment by kejunter** [comment]
Same problem, any solution? @luchuanqi Have you figured it out?

**Comment by wa292178** [comment]
any solution?

**Comment by Sazy67** [comment]
I'm looking for a solution to this problem. Can we please get support from the team?

**Comment by ShiSheng** [comment]
> my tracker synced ready like this ![image](https://private-user-images.githubusercontent.com/38414788/366381719-501f4f7a-d70d-4737-9511-01b068e4394b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwOTc5NTMsIm5iZiI6MTcyNjA5NzY1MywicGF0aCI6Ii8zODQxNDc4OC8zNjYzODE3MTktNTAxZjRmN2EtZDcwZC00NzM3LTk1MTEtMDFiMDY4ZTQzOTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDIzMzQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyZGVlYmM5YWY5MTZjYzk0ZjcyZjJkY2JiNDJlZDgwMWM4YTIwM2QzMDdiMzdiNjlhZjU2Zjc4YzUyYzRlN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1zOEho1oHaEDjrMUtw-iGoZF-VQGZJAdwNWnmHgDMk0)
> 
> but i still do not have tokens.json file
> 
> when this file generate

same question.
any solution?
@opcatbugcloser

**Comment by ShiSheng** [comment]
![image](https://github.com/user-attachments/assets/79e007a2-4736-4892-a263-9ba44c253ba3)

**Comment by macedo8** [comment]
![image](https://github.com/user-attachments/assets/c7b83f4f-ec7f-4b79-8d48-774975cdfd32)

**Comment by opcatbugcloser** [comment]
> my tracker synced ready like this ![image](https://private-user-images.githubusercontent.com/38414788/366381719-501f4f7a-d70d-4737-9511-01b068e4394b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0OTA1MzcsIm5iZiI6MTcyNjQ5MDIzNywicGF0aCI6Ii8zODQxNDc4OC8zNjYzODE3MTktNTAxZjRmN2EtZDcwZC00NzM3LTk1MTEtMDFiMDY4ZTQzOTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDEyMzcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjZWU0NDhmODljZGI0NGRmOTgzNDFkZTIyODkwMzRkYjJkMzU2ZmUyMTNjYTcyNjkwMDAwNTA4YzEzOWUzNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0yPiN61LwlUX4wSw_8E8HDrcUp-X-Vjix5FikCC13kw)
> 
> but i still do not have tokens.json file
> 
> when this file generate

need node user password correct
