### ISSUE TITLE
{"result":null,"error":{"code":-26,"message":"too-long-mempool-chain, too many unconfirmed ancestors [limit: 25]"},"id":"cat-cli"}

### ISSUE THREAD

**Issue by Musashi-great** [CATProtocol/cat-token-box#50]
![스크린샷 2024-09-12 221416](https://github.com/user-attachments/assets/5dd2ee02-d832-4d00-9df5-7e33ec2993f9)
keep showing this but there is no pending tx 
i check fractal explorer
should i need to make new account??

**Comment by opcatbugcloser** [comment]
This is because the bitcoin memory pool has a limit of 25 unconfirmed transactions, please wait for the transaction to be confirmed and try again
