### ISSUE TITLE
转账 send -i 提示 葱不够，但是手续费是够的

### ISSUE THREAD

**Issue by yutou123** [CATProtocol/cat-token-box#56]
yarn cli send -i 45ee725c2c5993b3e4d308842d87e973bf1951f5f7a804b21e4dd964ecd12d6b_0 地址 金额是1

![55555](https://github.com/user-attachments/assets/1f50d42d-7004-44a2-b5e8-28496a49c4f8)

**Comment by ArkChou** [comment]
I also encountered the same problem

**Comment by chaohui997** [comment]
一样，有解决方案吗？

**Comment by xueyuchen** [comment]
I also encountered the same problem

**Comment by MasterGG** [comment]
same problem for me
