### ISSUE TITLE
No token found for tokenId: 45ee725c2c5993b3e4d308842d87e973bf1951f5f7a804b21e4dd964ecd12d6b_0

### ISSUE THREAD

**Issue by prafullss** [CATProtocol/cat-token-box#58]
I encountered an issue where the token with **tokenId 45ee725c2c5993b3e4d308842d87e973bf1951f5f7a804b21e4dd964ecd12d6b_0** could not be found.

_Please advise on how this can be resolved or if additional steps are required on my end. Let me know if further details are needed._

**Comment by MBTimY** [comment]
cause of you didn't sync completely...

**Comment by prafullss** [comment]
exactly
