### ISSUE TITLE
Error: {"result":null,"error":{"code":-25,"message":"bad-txns-inputs-missingorspent"},"id":"cat-cli"}

### ISSUE THREAD

**Issue by 0Xmorgan888** [CATProtocol/cat-token-box#60]
mint command shows many time  "retry to mint token [CAT] ..." 

i add a console log after it and it shows this error : 
Error: {"result":null,"error":{"code":-25,"message":"bad-txns-inputs-missingorspent"},"id":"cat-cli"}

what it mean ?and why this happen ?

**Comment by opcatbugcloser** [comment]
The transaction uses the utxo that has been spent, and you can try to retry it later

**Comment by 0Xmorgan888** [comment]
> The transaction uses the utxo that has been spent, and you can try to retry it later

still have this issue 
how can i fix it ? 
and why this happen ?
