### ISSUE TITLE
sudo docker logs tracker -f | grep "block"  查询节点日志，报错，跪求大神！

### ISSUE THREAD

**Issue by beifang721** [CATProtocol/cat-token-box#67]
![image](https://github.com/user-attachments/assets/f23a1231-c46a-4060-937e-4ff3cbe0e275)
ERROR [RpcService] rpc error, Request failed with status code 503, {"jsonrpc":"1.0","id":1726195954670,"method":"getblockchaininfo","params":[]}
[Nest] 29  - 09/13/2024, 3:08:00 PM   ERROR [RpcService] rpc error, connect ECONNREFUSED 172.17.0.1:8332, {"jsonrpc":"1.0","id":1726211280598,"method":"getblockchaininfo","params":[]}
[Nest] 29  - 09/13/2024, 3:19:48 PM   ERROR [RpcService] rpc error, connect ECONNREFUSED 172.17.0.1:8332, {"jsonrpc":"1.0","id":1726211988438,"method":"getblockchaininfo","params":[]}
[Nest] 29  - 09/13/2024, 10:52:34 AM     LOG [BlockService] processed block #13706 f340115571eb95b58ae1b0b3f4251f85a4485deabc82f7a68d88ac93941cdbd5,  734 txs 20047 ms   37 tps,  617 txs 17179 ms   36 tps
[Nest] 29  - 09/13/2024, 3:20:03 PM   ERROR [RpcService] rpc error, connect ECONNREFUSED 172.17.0.1:8332, {"jsonrpc":"1.0","id":1726212003521,"method":"getblockchaininfo","params":[]}

**Comment by beifang721** [comment]
@opcatbugcloser @CATProtocol @holazz

**Comment by ts-sf** [comment]
What about the "postgres" logs?

**Comment by beifang721** [comment]
怎么执行这指令？

**Comment by opcatdev** [comment]
rpc connection error, check your fractal node
