### ISSUE TITLE
The transfer was initiated successfully but b was not received

### ISSUE THREAD

**Issue by ArkChou** [CATProtocol/cat-token-box#68]
I used the send command to initiate a transfer, and it was prompted that the transfer was successful and gave me the transaction hash, but it was not uploaded to the chain and my money was deducted.
This is the address where I initiate the transfer:bc1p8her9hltly0qfxrcwy9swqkqmc066lh7f0t2wykt7p7djq6vkrvsnre02m
This is the txhash the command receipt gave me:95d8f570b272fe9f7bcec9c0bbb4ac6618797616b9980315bdd0669409bca182

**Comment by ArkChou** [comment]
@opcatbugcloser

**Comment by opcatdev** [comment]
if the txHash is invalid in the end, then the token transfer will not happen
