### ISSUE TITLE
yarn cli wallet export 运行失败！

### ISSUE THREAD

**Issue by MarkSSH** [CATProtocol/cat-token-box#70]
旧钱包无法运行yarn cli wallet export，显示如下错误：
`rpc_importdescriptors failed!
Internal Server Error`

创建新钱包并导出后可以正常工作，但原来的钱包仍然不起作用
请帮助我解决一下，谢谢您！！！ @opcatbugcloser

**Comment by lly835** [comment]
name是跟节点绑定的，助记词可以更换。

**Comment by MarkSSH** [comment]
> name是跟节点绑定的，助记词可以更换。

您好！这是什么意思呢？我尝试过直接替换wallet.json的文件内容直接替换cli下的钱包，其他的钱包都没问题，只有最早创建的钱包不能执行这个，会是什么原因呢？

**Comment by ts-sf** [comment]
try `yarn cli wallet export --create=true` ?
