### ISSUE TITLE
"non-mandatory-script-verify-flag (Script failed an OP_EQUALVERIFY operation

### ISSUE THREAD

**Issue by somethingbeta** [CATProtocol/cat-token-box#72]
seem to get a lot of these, every 2/3 attempts, usually then succeeds after a couple of retries when running mints. 

{"result":null,"error":{"code":-26,"message":"non-mandatory-script-verify-flag (Script failed an OP_EQUALVERIFY operation)"},"id":"cat-cli"}

any ideas please. 

both the node and the cli are running on the same machine.

**Comment by usman-hypermint** [comment]
I am getting the same issue

**Comment by KingMaxime** [comment]
i also have the same issue

**Comment by gabr1234iel** [comment]
same issue on my end, transactions seem to be stuck at either:

`broadcast tx failed! Error: {"result":null,"error":{"code":-25,"message":"bad-txns-inputs-missingorspent"},"id":"cat-cli"}`
or
`broadcast tx failed! Error: {"result":null,"error":{"code":-26,"message":"non-mandatory-script-verify-flag (Script failed an OP_EQUALVERIFY operation)"},"id":"cat-cli"}`

**Comment by ikarus-bv** [comment]
> same issue on my end, transactions seem to be stuck at either:
> 
> `broadcast tx failed! Error: {"result":null,"error":{"code":-25,"message":"bad-txns-inputs-missingorspent"},"id":"cat-cli"}` or `broadcast tx failed! Error: {"result":null,"error":{"code":-26,"message":"non-mandatory-script-verify-flag (Script failed an OP_EQUALVERIFY operation)"},"id":"cat-cli"}`

**Same issue here!** for hours now. FB mainnet node fully synced, working. Tracker fully synced, working. Node fucked up. 

Also, cat node trying to submit 0.1 CAT tx to the FB mainnet since this morning, which is I guess breaking the protocol. 

Anyway, devs don't care, there are many issues with the node, that are referenced in other issues here and they did not address any of those nor they released the fixed cat node. This is sad state of crypto.

**Comment by arenouf14** [comment]
same issue here...

**Comment by gabr1234iel** [comment]
This too:

fetch minters failed, minter: bc1pqw9ncs4sna0ndh85ux5dhh9swueyjql23t4em8j0smywkqsngfmsn7gmua
fetch open minter state failed, minter: bc1pqw9ncs4sna0ndh85ux5dhh9swueyjql23t4em8j0smywkqsngfmsn7gmua, txId: 4ec99f85763d92b2c796d7b3605a924f24ed1249a95fe054bb37af653f54572e error

**Comment by gaohongxiang** [comment]
Same issue

**Comment by travieso1208-git** [comment]
same issue anyone know how to fix or is it out of our hands ?

**Comment by MarkSSH** [comment]
same issue, how to fix

**Comment by somethingbeta** [comment]
> This too:
> 
> fetch minters failed, minter: bc1pqw9ncs4sna0ndh85ux5dhh9swueyjql23t4em8j0smywkqsngfmsn7gmua fetch open minter state failed, minter: bc1pqw9ncs4sna0ndh85ux5dhh9swueyjql23t4em8j0smywkqsngfmsn7gmua, txId: 4ec99f85763d92b2c796d7b3605a924f24ed1249a95fe054bb37af653f54572e error

this has been happening to me too now .. I'm going to give up in a bit .. he he

**Comment by albertzzzzzzzzzzzz** [comment]
有解决方法不

**Comment by somethingbeta** [comment]
strange .. one just went through .. but i got a cat balance of 0.01 .. before was getting 5

**Comment by jiafu83** [comment]
seems protocol issue, invalid UTXO

**Comment by AlperKaraman** [comment]
Same issue

mint token [CAT] failed
{"result":null,"error":{"code":-26,"message":"non-mandatory-script-verify-flag (Script failed an OP_EQUALVERIFY operation)"},"id":"cat-cli"}

**Comment by somethingbeta** [comment]
Haven't dug into the verification itself, but this looks like a "concurrency" I am now running on a loop .. and so far hitting around 1 in 20 runs ..

**Comment by 0Xmorgan888** [comment]
> > same issue on my end, transactions seem to be stuck at either:
> > `broadcast tx failed! Error: {"result":null,"error":{"code":-25,"message":"bad-txns-inputs-missingorspent"},"id":"cat-cli"}` or `broadcast tx failed! Error: {"result":null,"error":{"code":-26,"message":"non-mandatory-script-verify-flag (Script failed an OP_EQUALVERIFY operation)"},"id":"cat-cli"}`
> 
> **Same issue here!** for hours now. FB mainnet node fully synced, working. Tracker fully synced, working. Node fucked up.

can you tell me how your tracker got synced ? 
mine track one block and miners mine two block ! it cant sync like that 
i have good cpu and ram

**Comment by 0Xmorgan888** [comment]
> same issue on my end, transactions seem to be stuck at either:
> 
> `broadcast tx failed! Error: {"result":null,"error":{"code":-25,"message":"bad-txns-inputs-missingorspent"},"id":"cat-cli"}` or `broadcast tx failed! Error: {"result":null,"error":{"code":-26,"message":"non-mandatory-script-verify-flag (Script failed an OP_EQUALVERIFY operation)"},"id":"cat-cli"}`

same issue ...

**Comment by Kenno88** [comment]
same here

**Comment by opcatdev** [comment]
a cli bug not protocol, already fixed before.
