### ISSUE TITLE
Viruses kdevtmpfsi and kinsing on packages/tracker/docker-compose.yml

### ISSUE THREAD

**Issue by plvo** [CATProtocol/cat-token-box#73]
I'm running on Ubuntu 22.04.

Since yesterday, my machine has been running the `kdevtmpfsi` and `kinsing` viruses. When I search for them, I find that they come from Docker (the Docker on this machine only runs the three project images).

The process of both viruses and especially `kdevtmpfsi` takes **100% of CPU performance** (screen btop).
![image](https://github.com/user-attachments/assets/dce7a6c2-d122-4bfa-bc2a-e22bb2fb6fbb)
Yesterday I tried to stop it, and succeeded by uninstalling Docker directly, but after reconfiguring the repo, the processes reappeared.

I saw that you're using the postgres:16 image:
https://github.com/CATProtocol/cat-token-box/blob/9ed9e01845573fe47e967c53d8e5c15babea38b8/packages/tracker/docker-compose.yml#L3
I found a very similar issue on the registery Docker Postgres repo: https://github.com/docker-library/postgres/issues/1054

**Comment by damianharouff** [comment]
Yup. I posted it here already: https://github.com/CATProtocol/cat-token-box/issues/49

**Comment by GaloisField2718** [comment]
Have you changed every passwords in .env and tracker/docker/Bitcoin.conf?

**Comment by damianharouff** [comment]
I have not. I don't run this garbage. I'm only a victim of the incompetence of whomever put together the instructions. 

The documentation page: https://github.com/CATProtocol/cat-token-box/blob/6d411914d59576363d0e6a1ddfe21d5bad8076d1/packages/tracker/README.md?plain=1#L23 only states "Update with your own configuration". There's no statement to change every password in .env, and there's no statement at all to modify Bitcoin.conf. 

Even if there were instructions, they won't be read by people just blindly copy and pasting the command blocks in a hurry to get to their FREE money.

**Comment by GaloisField2718** [comment]
Haha yes really not clear I updated on my branch.

**Comment by kagechio** [comment]
how to fully remove this sh1t? 
Unfortunately, I'm running this on a server that is used to run other projects 💀

**Comment by GaloisField2718** [comment]
Normal.... first check for docker running with 
```
docker ps -a
```

Look for Postgres:16, fractal-... and tracker. 
Copy the id of each container and do 
```
docker stop ID && docker remove ID
```

When you did this everything should be well removed.

**Comment by kagechio** [comment]
> Normal.... first check for docker running with
> 
> ```
> docker ps -a
> ```
> 
> Look for Postgres:16, fractal-... and tracker. Copy the id of each container and do
> 
> ```
> docker stop ID && docker remove ID
> ```
> 
> When you did this everything should be well removed.

Thank You. CPU load is normal now. I'll let you know in a few hours if this doesn't come back

**Comment by plvo** [comment]
@kagechio if it reappears, and you can afford it, delete docker directly from your machine. It worked for me.

**Comment by damianharouff** [comment]
Yes good, throw everything away. :)

**Comment by kagechio** [comment]
> @kagechio if it reappears, and you can afford it, delete docker directly from your machine. It worked for me.

That shit ain't coming back bro, thanks a lot @plvo @GaloisField2718 @damianharouff  gbu

**Comment by kagechio** [comment]
![{33668D8A-2DB7-407E-998F-8605FC5A261D}](https://github.com/user-attachments/assets/a4eb56ae-dea8-4ffe-9d6a-d4c25359f5cb)

**Comment by tushar1977** [comment]
first to do docker exec to enter to postgras , then go to /var/lib/postgresql/data/pgdata/pg_hba.conf and change host all all all scram-sha-256 to host all all all md5
then  restart postgras container
do this to run tracker
sudo docker run -d \
    --name tracker \
    --add-host="host.docker.internal:host-gateway" \
    -e DATABASE_HOST="host.docker.internal" \
    -e RPC_HOST="host.docker.internal" \
    -e DATABASE_USERNAME="postgres" \
    -e DATABASE_PASSWORD="your_pass_that is entered in .env" \
    -e DATABASE_DB="postgres" \
    -p 3000:3000 \
    tracker:latest

**Comment by damianharouff** [comment]
Other than making this situation worse, what's the point of reducing security by changing from one secure cipher to a very insecure cipher?

**Comment by tushar1977** [comment]
> Other than making this situation worse, what's the point of reducing security by changing from one secure cipher to a very insecure cipher?

any solution ?

**Comment by tushar1977** [comment]
> ![image](https://private-user-images.githubusercontent.com/2953243/369619564-1fe8dcbf-2b2a-4936-a44d-0f0e9f152e1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5OTE3MDUsIm5iZiI6MTcyNjk5MTQwNSwicGF0aCI6Ii8yOTUzMjQzLzM2OTYxOTU2NC0xZmU4ZGNiZi0yYjJhLTQ5MzYtYTQ0ZC0wZjBlOWYxNTJlMWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjJUMDc1MDA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjdhNTNkOWEwMTY1MzZiZDUwODJhOWEwOTkxODZmYjI5ZWE4ZmFmNWE2YjliYzBkZjJlNjNlYjU1MmI0NjAwMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.z0hriYjIyR3zFGDi49Spgd4fB84nnDhDJuNh7E_kZlE)


ok i tempory stopped by enabling ufw and only allowing specific ports and changed my postgres password

**Comment by opcatdev** [comment]
#134
