### ISSUE TITLE
transfer program Insufficient satoshis balance! 国产垃圾项目吗 这么多bug 我钱包里面有钱啊

### ISSUE THREAD

**Issue by LinBBB** [CATProtocol/cat-token-box#74]
![image](https://github.com/user-attachments/assets/d8131263-76ad-4b10-9440-edd94bab71fc)
![image](https://github.com/user-attachments/assets/d8131263-76ad-4b10-9440-edd94bab71fc)
![image](https://github.com/user-attachments/assets/d8131263-76ad-4b10-9440-edd94bab71fc)

**Comment by chaohui997** [comment]
这个问题，有大兄弟有解决方案吗

**Comment by lly835** [comment]
节点同步问题

**Comment by hotbroker** [comment]
> 这个问题，有大兄弟有解决方案吗

知道，解决了，改了配置

**Comment by zhourunjun** [comment]
> 知道，解决了，改了配置

咋改啊？大兄弟

**Comment by qianduanPP** [comment]
> > 知道了，解决了，改了配置
怎么改的？能说一下吗？谢谢

**Comment by CSWellesSun** [comment]
怎么改？有兄弟知道的吗

**Comment by sfhoo** [comment]
To fix this issue, you need to do
yarn cli wallet export --create=true under packages/cli
then do this
./bitcoin-cli rescanblockchain under fractal bitcode node /bin
