### ISSUE TITLE
我给了3400的gas你就帮我mint 0.01 CAT？

### ISSUE THREAD

**Issue by lly835** [CATProtocol/cat-token-box#76]
<img width="1292" alt="image" src="https://github.com/user-attachments/assets/9e01fa3f-0174-4597-bb30-03baf8a9dea8">

**Comment by gaohongxiang** [comment]
<img width="558" alt="image" src="https://github.com/user-attachments/assets/4c15db37-54bc-47c8-96c3-382f2f317124">
你这个情况是存在的，运气不好。

<img width="1223" alt="image" src="https://github.com/user-attachments/assets/4334e17a-c57c-4a38-99ef-770b7d61a304">
兄弟有没有遇到这个问题？

**Comment by lly835** [comment]
不是运气不好，当90%的人开始打4.99,   0.01的概率就大了

**Comment by gabr1234iel** [comment]
我刚刚中奖了，全部 failed tx 只有0.01 的通过了 
![Uploading Screenshot 2024-09-13 at 8.41.08 PM.png…]()
wc

**Comment by SexyERIC0723** [comment]
> <img alt="image" width="558" src="https://private-user-images.githubusercontent.com/33713367/367293510-4c15db37-54bc-47c8-96c3-382f2f317124.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMzMyMDEsIm5iZiI6MTcyNjIzMjkwMSwicGF0aCI6Ii8zMzcxMzM2Ny8zNjcyOTM1MTAtNGMxNWRiMzctNTRiYy00N2M4LTk2YzMtMzgyZjJmMzE3MTI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDEzMDgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiMzI5YjBkOTJhN2NkMjk5ZjEwZTcxYjYxYzEyMDEyNzc0OWZjZTZjZmU2NTJhNjFlMjk3ZDgyM2IyYjlkYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VbQC1Cew-9vszuphI2GyFWaqIfMjzrtaSPuwkucfg8I"> 你这个情况是存在的，运气不好。 <img alt="image" width="1223" src="https://private-user-images.githubusercontent.com/33713367/367292944-4334e17a-c57c-4a38-99ef-770b7d61a304.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMzMyMDEsIm5iZiI6MTcyNjIzMjkwMSwicGF0aCI6Ii8zMzcxMzM2Ny8zNjcyOTI5NDQtNDMzNGUxN2EtYzU3Yy00YTM4LTk5ZWYtNzcwYjdkNjFhMzA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDEzMDgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmNzM3ZDkyNmEyMzRiNDAyYjAwNmU0YzUzODlmODM4YjNlNTlhMzc1MjBkYWJiMjVjNjBiMDg4ZWUzMzhjYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.az68lduNA_T2qDDjz3SlrLnfToq564PhR79NEaPURUQ"> 兄弟有没有遇到这个问题？

我也这样是怎么回事啊

**Comment by SexyERIC0723** [comment]
<img width="117" alt="image" src="https://github.com/user-attachments/assets/21537c81-9134-433e-8c21-c2b5fe4d7a39">
难崩啊兄弟们0.01 世上还是坏人多

**Comment by 666-eth** [comment]
最后怎么解决呢

**Comment by lly835** [comment]
自己改mint代码。
```
if (amount !== 500n) {
       console.error(amount);
       return;
}
const mintTxIdOrErr = await (0, ft_open_minter_1.openMint)(this.configService, this.walletService, this.spendService, feeRate, feeUtxos, token, 2, minter, amount);
```

**Comment by crackeryo** [comment]
compile 的时候出现 error TS2304: Cannot find name 'ft_open_minter_1'.咋办

**Comment by arenouf14** [comment]
> compile 的时候出现 error TS2304: Cannot find name 'ft_open_minter_1'.咋办

@crackeryo  you have to change the code in the dist folder directly I think so you dont re-compile (if I understand correctly the proposal and after looking for the piece of code with ft_open_minter_1

**Comment by crackeryo** [comment]
> > compile 的时候出现 error TS2304: Cannot find name 'ft_open_minter_1'.咋办
> 
> @crackeryo you have to change the code in the dist folder directly I think so you dont re-compile (if I understand correctly the proposal and after looking for the piece of code with ft_open_minter_1

got it! just figured it out. 
Changing uncompiled the code and re-compiling works as well. 

does any oneany idea how to go around with the issue of {"result":null,"error":{"code":-26,"message":"non-mandatory-script-verify-flag (Script failed an OP_EQUALVERIFY operation)"},"id":"cat-cli"} ?

**Comment by crackeryo** [comment]
> > compile 的时候出现 error TS2304: Cannot find name 'ft_open_minter_1'.咋办
> 
> @crackeryo you have to change the code in the dist folder directly I think so you dont re-compile (if I understand correctly the proposal and after looking for the piece of code with ft_open_minter_1

have anyone tried changing the amount directly if it doesn't match, what will happen?有人试过直接改数量吗，会发生什么
