### ISSUE TITLE
【必看】踩坑日记

### ISSUE THREAD

**Issue by lly835** [CATProtocol/cat-token-box#77]
#### 方案：直接改build后的mint的代码，路径 packages/cli/dist/commands/mint/mint.command.js
```
if (amount !== 500n) {
       console.error(amount);
       return;
}
const mintTxIdOrErr = await (0, ft_open_minter_1.openMint)(this.configService, this.walletService, this.spendService, feeRate, feeUtxos, token, 2, minter, amount);
```

**Comment by SexyERIC0723** [comment]
<img width="991" alt="image" src="https://github.com/user-attachments/assets/e37dd51e-acb2-434b-8ac9-a7c6bb128c33">
同步了一天没打几个出现这问题

**Comment by MarkSSH** [comment]
> <img alt="image" width="991" src="https://private-user-images.githubusercontent.com/85037553/367306912-e37dd51e-acb2-434b-8ac9-a7c6bb128c33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMzMzNDQsIm5iZiI6MTcyNjIzMzA0NCwicGF0aCI6Ii84NTAzNzU1My8zNjczMDY5MTItZTM3ZGQ1MWUtYWNiMi00MzRiLThhYzktYTdjNmJiMTI4YzMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDEzMTA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1ODZhY2EwNzYzNzU2MDRlYjMzNzc2ZGE1YmYzN2IwZDA0OWMwMGZiODJiYzE1MzcwOTI0MmY3Mzg0NDQ5NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WJn5gAsa-mwVs3CDYT5A4vqySA6o17xIm6rnDIXxGHw"> 同步了一天没打几个出现这问题

+1，现在每一个成的，全是这个问题

**Comment by gabr1234iel** [comment]
stash 了后跑了git pull， 现在出这个：
```{"result":null,"error":{"code":-26,"message":"non-mandatory-script-verify-flag (Script failed an OP_EQUALVERIFY operation)"},"id":"cat-cli"}```

**Comment by SexyERIC0723** [comment]
> ## 开个帖子，记录踩坑和解决方案！
> ### 1. 如何避免mint 0.01 CAT
> #### 方案：改mint的代码
> ```
> if (amount !== 500n) {
>        console.error(amount);
>        return;
> }
> const mintTxIdOrErr = await (0, ft_open_minter_1.openMint)(this.configService, this.walletService, this.spendService, feeRate, feeUtxos, token, 2, minter, amount);
> ```

哥这个要添加在哪里呀

**Comment by 0JustinTang0** [comment]
能在tracker侧修改吗？

**Comment by ThreeAndTwo** [comment]
> 代码路径在哪里？

cat-token-box/packages/cli/src/commands/mint/mint.command.ts

**Comment by ThreeAndTwo** [comment]
> 能在tracker侧修改吗？

设计上不应该懂 tracker 的代码，trcker 是个索引器，至于你选不选择这个索引，应该逻辑端筛选。

**Comment by albertzzzzzzzzzzzz** [comment]
添加在文件那个位置？

**Comment by lly835** [comment]
> > ## 开个帖子，记录踩坑和解决方案！
> > ### 1. 如何避免mint 0.01 CAT
> > #### 方案：改mint的代码
> > ```
> > if (amount !== 500n) {
> >        console.error(amount);
> >        return;
> > }
> > const mintTxIdOrErr = await (0, ft_open_minter_1.openMint)(this.configService, this.walletService, this.spendService, feeRate, feeUtxos, token, 2, minter, amount);
> > ```
> 
> 哥这个要添加在哪里呀
packages/cli/dist/commands/mint/mint.command.js

**Comment by hardwin1014** [comment]
好慢啊，有解决办法吗
