### ISSUE TITLE
Why is the address different from the address in the program after I import the mnemonic into unisat?

### ISSUE THREAD

**Issue by ggkkwom** [CATProtocol/cat-token-box#8]
Why is the address different from the address in the program after I import the mnemonic into unisat?

![image](https://github.com/user-attachments/assets/b55c3d16-26e6-48e1-ae28-755ff4f6fe0f)

![image](https://github.com/user-attachments/assets/903b651b-1d92-42dc-a542-439084ea525c)

**Comment by opcatbugcloser** [comment]
The HD-derived path of the project is different from unisat

**Comment by CATProtocol** [comment]
Now the same https://github.com/CATProtocol/cat-token-box/commit/cb0a7e382ef9defb8a2477eb3b116c029ae03a09
