### ISSUE TITLE
Merge [CAT] tokens failed.

### ISSUE THREAD

**Issue by Zcompzhe** [CATProtocol/cat-token-box#85]
Merge [CAT] tokens failed.
broadcast merge token txs failed, {"result":null,"error":{"code":-25,"message":"bad-txns-inputs-missingorspent"},"id":"cat-cli"}

![image](https://github.com/user-attachments/assets/ff16a2af-9b6a-45ad-8a24-275a96d201ea)

**Comment by 0Xmorgan888** [comment]
Error: {"result":null,"error":{"code":-25,"message":"bad-txns-inputs-missingorspent"},"id":"cat-cli"}


same error !

**Comment by hardwin1014** [comment]
合并了38组，一共300多个UTXO，花了1.3FB

**Comment by kejunter** [comment]
> broadcast merge token txs failed
这个问题解决了吗？我也是这个问题
