### ISSUE TITLE
too-long-mempool-chain, too many unconfirmed ancestors 

### ISSUE THREAD

**Issue by 491600092** [CATProtocol/cat-token-box#9]
![image](https://github.com/user-attachments/assets/0ad14568-02ea-462c-a99c-39494554d5fe)
mint token [CAT] failed
{"result":null,"error":{"code":-26,"message":"too-long-mempool-chain, too many unconfirmed ancestors [limit: 25]"},"id":"cat-cli"}

**Comment by opcatbugcloser** [comment]
Wait for the transaction to block, or deploy a new account

**Comment by hodor1511** [comment]
> Wait for the transaction to block, or deploy a new account

hey man, i faced the same issuse, and want to know all the cli commands, where can i find it? i mean the cli command document

**Comment by hodor1511** [comment]
how to export new address to RPC node

**Comment by hodor1511** [comment]
> how to export new address to RPC node

yarn cli wallet export

GOT IT

**Comment by hodor1511** [comment]
![image](https://github.com/user-attachments/assets/29e1eca8-acb6-4573-a95c-9267a4e0b7a1)
i try to create a new wallet and exported it successfully,
but question still
