### ISSUE TITLE
Insufficient token balance!

### ISSUE THREAD

**Issue by xly9984760** [CATProtocol/cat-token-box#90]
转账报错，但是查询余额发现 Cat 余额足够，我接下来应该怎么做呢？
```
root@iZt4n0yp5lirsc5Z:~/cat-token-box/packages/cli# sudo yarn cli send -i 45ee725c2c5993b3e4d308842d87e973bf1951f5f7a804b21e4dd964ecd12d6b_0 bc1pzyrztk9qp4rdpvqfzhzv39u2dylw2ffhs4l722qx79quj79katwskr2h5f 100
yarn run v1.22.22
$ node dist/main send -i 45ee725c2c5993b3e4d308842d87e973bf1951f5f7a804b21e4dd964ecd12d6b_0 bc1pzyrztk9qp4rdpvqfzhzv39u2dylw2ffhs4l722qx79quj79katwskr2h5f 100
Insufficient token balance!
Done in 0.98s.
```

**Comment by whalefrat** [comment]
我也遇到了

**Comment by sslisen** [comment]
同样的问题，即使使用export命令把导入钱包 exporting到RPC节点，也还是会报错。

**Comment by xly9984760** [comment]
更新进展，发现我是转账成功的，但是过了将就6、7个小时。导致我转账过多

**Comment by sslisen** [comment]
> 更新进展，发现我是转账成功的，但是过了将近6、7个小时。导致我转账过多，有什么办法快速 confirm 吗

我的问题是，第一次转账成功了。但是我只转了一部分CAT出去，然后进行第二次转账时，就开始报：insufficient token balance的错误，目前还没解决。

**Comment by sslisen** [comment]
> 更新进展，发现我是转账成功的，但是过了将近6、7个小时。导致我转账过多，有什么办法快速 confirm 吗

请问，你之前这个token balance问题是如何解决的，也就是操作了什么，使得转账成功了？

**Comment by xly9984760** [comment]
什么操作都没做，我的情况是前面有做 send 操作，扣除了 余额，但是交易在mempool，没有进一步confirm。这个时候我继续转账提示我余额不足。过了几个小时，节点 confirm 就转过去了

**Comment by sslisen** [comment]
> 什么操作都没做，我的情况是前面有做 send 操作，扣除了 余额，但是交易在mempool，没有进一步confirm。这个时候我继续转账提示我余额不足。过了几个小时，节点 confirm 就转过去了

好的，那我们的问题还不一样。我是第一次转账很快，gas给低了， 等了几个块就过了。然后发起第二笔转账时，就一直报 token balances错误。

**Comment by catdev2024** [comment]
> > 更新进展，发现我是转账成功的，但是过了将近6、7个小时。导致我转账过多，有什么办法快速 confirm 吗
> 
> 我的问题是，第一次转账成功了。但是我只转了一部分CAT出去，然后进行第二次转账时，就开始报：insufficient token balance的错误，目前还没解决。

你可能是只有一个token UTXO. 你前面转账一部分CAT出去，剩下的会产生新的token UTXO.  但是这笔转账还没入块，tracker还没索引到新产生的token utxo ，就会报余额不足。等你前面的交易入块就可以了

**Comment by sslisen** [comment]
> > > 更新进展，发现我是转账成功的，但是过了将近6、7个小时。导致我转账过多，有什么办法快速 confirm 吗
> > 
> > 
> > 我的问题是，第一次转账成功了。但是我只转了一部分CAT出去，然后进行第二次转账时，就开始报：insufficient token balance的错误，目前还没解决。
> 
> 你可能是只有一个token UTXO. 你前面转账一部分CAT出去，剩下的会产生新的token UTXO. 但是这笔转账还没入块，tracker还没索引到新产生的token utxo ，就会报余额不足。等你前面的交易入块就可以了

好的，感谢解答。
我这边发现问题了，是因为打的时候 没有使用合并的方式打。所以导致utxo过多，如果转账数量超过500个CAT，就会报错。如果控制在500以内，就不会报错。

**Comment by shizz-x** [comment]
https://github.com/CATProtocol/cat-token-box/issues/110
