### ISSUE TITLE
The node is not synchronized

### ISSUE THREAD

**Issue by groomiee** [CATProtocol/cat-token-box#91]
I launched the node for synchronization but I always see this status.

{"code":0,"msg":"OK","data":{"trackerBlockHeight":null,"nodeBlockHeight":null,"latestBlockHeight":null}}

I am attaching the logs

[compose_logs.txt](https://github.com/user-attachments/files/17003850/compose_logs.txt)

[tracker_logs.txt](https://github.com/user-attachments/files/17003851/tracker_logs.txt)

**Comment by opcatbugcloser** [comment]
Need node user password correct

**Comment by dqminh100** [comment]
i have same issue. pls help me fix it
