### ISSUE TITLE
No available minter UTXO found!

### ISSUE THREAD

**Issue by sanyalaurent** [CATProtocol/cat-token-box#93]
After i try to mint with
 ///sudo yarn cli mint -i 45ee725c2c5993b3e4d308842d87e973bf1951f5f7a804b21e4dd964ecd12d6b_0 5 --fee-rate $(curl -s https://explorer.unisat.io/fractal-mainnet/api/bitcoin-info/fee | jq '.data.fastestFee')///
i have an error "No available minter UTXO found!"
![image](https://github.com/user-attachments/assets/3413003e-f28d-4cad-b937-b3458fa67e56)
also i have 3.4FB in my connected wallet
![image](https://github.com/user-attachments/assets/da5b1f49-3658-4a9e-b5cb-92c8ec0beb5a)

**Comment by opcatbugcloser** [comment]
Need tracker synced
