### ISSUE TITLE
[mint bug]现在的mint合约未检查minter input数量，导致mint过程中可mint数量减少

### ISSUE THREAD

**Issue by ipoh123** [CATProtocol/cat-token-box#97]
参见这条交易：https://mempool.fractalbitcoin.io/tx/1cca37aee4853315ba9039392f8af7962c8209adedb56d61e6165ed6c5688988
可能导致mint过程中可mint数量减少

协议文档也有规定：There is exactly one minter input

**Comment by opcatdev** [comment]
don't understand
